### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by op7ic** [EbryxLabs/__DFIR-scripts#1]
As requested:

Hi Guys,

great tool. It would be useful to have it working on cygwin too. Default windows works just fine but paths etc gets messed up when using Cygwin

**Comment by RogueContact** [comment]
Applied a fix for paths based on OS. Please consider closing the issue if you think its resolved.

**Comment by ahmadmkhan1** [comment]
Applied a fix for paths based on OS. Please consider closing the issue if you think its resolved.
